/*
 * Catalog Inventory
 * Catalog Inventory
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.ErrorNotFound;
import org.openapitools.client.model.ServiceInventoriesCollection;
import org.openapitools.client.model.ServiceInventory;
import org.openapitools.client.model.Tag;
import org.openapitools.client.model.TagsCollection;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ServiceInventoryApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public ServiceInventoryApi() {
        this(Configuration.getDefaultApiClient());
    }

    public ServiceInventoryApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for listServiceInventories
     * @param limit The numbers of items to return per page. (optional, default to 100)
     * @param offset The number of items to skip before starting to collect the result set. (optional, default to 0)
     * @param filter Filter for querying collections. (optional)
     * @param sortBy The list of attribute and order to sort the result set by. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> ServiceInventories collection </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listServiceInventoriesCall(@javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, @javax.annotation.Nullable Object filter, @javax.annotation.Nullable Object sortBy, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/service_inventories";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        if (offset != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("offset", offset));
        }

        if (filter != null) {
            localVarQueryParams.addAll(localVarApiClient.freeFormParameterToPairs(filter));
        }

        if (sortBy != null) {
            localVarQueryParams.addAll(localVarApiClient.freeFormParameterToPairs(sortBy));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "UserSecurity" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listServiceInventoriesValidateBeforeCall(@javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, @javax.annotation.Nullable Object filter, @javax.annotation.Nullable Object sortBy, final ApiCallback _callback) throws ApiException {
        return listServiceInventoriesCall(limit, offset, filter, sortBy, _callback);

    }

    /**
     * List ServiceInventories
     * Returns an array of ServiceInventory objects
     * @param limit The numbers of items to return per page. (optional, default to 100)
     * @param offset The number of items to skip before starting to collect the result set. (optional, default to 0)
     * @param filter Filter for querying collections. (optional)
     * @param sortBy The list of attribute and order to sort the result set by. (optional)
     * @return ServiceInventoriesCollection
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> ServiceInventories collection </td><td>  -  </td></tr>
     </table>
     */
    public ServiceInventoriesCollection listServiceInventories(@javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, @javax.annotation.Nullable Object filter, @javax.annotation.Nullable Object sortBy) throws ApiException {
        ApiResponse<ServiceInventoriesCollection> localVarResp = listServiceInventoriesWithHttpInfo(limit, offset, filter, sortBy);
        return localVarResp.getData();
    }

    /**
     * List ServiceInventories
     * Returns an array of ServiceInventory objects
     * @param limit The numbers of items to return per page. (optional, default to 100)
     * @param offset The number of items to skip before starting to collect the result set. (optional, default to 0)
     * @param filter Filter for querying collections. (optional)
     * @param sortBy The list of attribute and order to sort the result set by. (optional)
     * @return ApiResponse&lt;ServiceInventoriesCollection&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> ServiceInventories collection </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ServiceInventoriesCollection> listServiceInventoriesWithHttpInfo(@javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, @javax.annotation.Nullable Object filter, @javax.annotation.Nullable Object sortBy) throws ApiException {
        okhttp3.Call localVarCall = listServiceInventoriesValidateBeforeCall(limit, offset, filter, sortBy, null);
        Type localVarReturnType = new TypeToken<ServiceInventoriesCollection>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List ServiceInventories (asynchronously)
     * Returns an array of ServiceInventory objects
     * @param limit The numbers of items to return per page. (optional, default to 100)
     * @param offset The number of items to skip before starting to collect the result set. (optional, default to 0)
     * @param filter Filter for querying collections. (optional)
     * @param sortBy The list of attribute and order to sort the result set by. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> ServiceInventories collection </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listServiceInventoriesAsync(@javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, @javax.annotation.Nullable Object filter, @javax.annotation.Nullable Object sortBy, final ApiCallback<ServiceInventoriesCollection> _callback) throws ApiException {

        okhttp3.Call localVarCall = listServiceInventoriesValidateBeforeCall(limit, offset, filter, sortBy, _callback);
        Type localVarReturnType = new TypeToken<ServiceInventoriesCollection>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for listServiceInventoryTags
     * @param id ID of the resource (required)
     * @param limit The numbers of items to return per page. (optional, default to 100)
     * @param offset The number of items to skip before starting to collect the result set. (optional, default to 0)
     * @param filter Filter for querying collections. (optional)
     * @param sortBy The list of attribute and order to sort the result set by. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Tags collection </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listServiceInventoryTagsCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, @javax.annotation.Nullable Object filter, @javax.annotation.Nullable Object sortBy, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/service_inventories/{id}/tags"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (limit != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("limit", limit));
        }

        if (offset != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("offset", offset));
        }

        if (filter != null) {
            localVarQueryParams.addAll(localVarApiClient.freeFormParameterToPairs(filter));
        }

        if (sortBy != null) {
            localVarQueryParams.addAll(localVarApiClient.freeFormParameterToPairs(sortBy));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "UserSecurity" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listServiceInventoryTagsValidateBeforeCall(@javax.annotation.Nonnull String id, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, @javax.annotation.Nullable Object filter, @javax.annotation.Nullable Object sortBy, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling listServiceInventoryTags(Async)");
        }

        return listServiceInventoryTagsCall(id, limit, offset, filter, sortBy, _callback);

    }

    /**
     * List Tags for ServiceInventory
     * Returns an array of Tag objects
     * @param id ID of the resource (required)
     * @param limit The numbers of items to return per page. (optional, default to 100)
     * @param offset The number of items to skip before starting to collect the result set. (optional, default to 0)
     * @param filter Filter for querying collections. (optional)
     * @param sortBy The list of attribute and order to sort the result set by. (optional)
     * @return TagsCollection
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Tags collection </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public TagsCollection listServiceInventoryTags(@javax.annotation.Nonnull String id, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, @javax.annotation.Nullable Object filter, @javax.annotation.Nullable Object sortBy) throws ApiException {
        ApiResponse<TagsCollection> localVarResp = listServiceInventoryTagsWithHttpInfo(id, limit, offset, filter, sortBy);
        return localVarResp.getData();
    }

    /**
     * List Tags for ServiceInventory
     * Returns an array of Tag objects
     * @param id ID of the resource (required)
     * @param limit The numbers of items to return per page. (optional, default to 100)
     * @param offset The number of items to skip before starting to collect the result set. (optional, default to 0)
     * @param filter Filter for querying collections. (optional)
     * @param sortBy The list of attribute and order to sort the result set by. (optional)
     * @return ApiResponse&lt;TagsCollection&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Tags collection </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<TagsCollection> listServiceInventoryTagsWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, @javax.annotation.Nullable Object filter, @javax.annotation.Nullable Object sortBy) throws ApiException {
        okhttp3.Call localVarCall = listServiceInventoryTagsValidateBeforeCall(id, limit, offset, filter, sortBy, null);
        Type localVarReturnType = new TypeToken<TagsCollection>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List Tags for ServiceInventory (asynchronously)
     * Returns an array of Tag objects
     * @param id ID of the resource (required)
     * @param limit The numbers of items to return per page. (optional, default to 100)
     * @param offset The number of items to skip before starting to collect the result set. (optional, default to 0)
     * @param filter Filter for querying collections. (optional)
     * @param sortBy The list of attribute and order to sort the result set by. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Tags collection </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listServiceInventoryTagsAsync(@javax.annotation.Nonnull String id, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, @javax.annotation.Nullable Object filter, @javax.annotation.Nullable Object sortBy, final ApiCallback<TagsCollection> _callback) throws ApiException {

        okhttp3.Call localVarCall = listServiceInventoryTagsValidateBeforeCall(id, limit, offset, filter, sortBy, _callback);
        Type localVarReturnType = new TypeToken<TagsCollection>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for showServiceInventory
     * @param id ID of the resource (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> ServiceInventory info </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call showServiceInventoryCall(@javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/service_inventories/{id}"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "UserSecurity" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call showServiceInventoryValidateBeforeCall(@javax.annotation.Nonnull String id, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling showServiceInventory(Async)");
        }

        return showServiceInventoryCall(id, _callback);

    }

    /**
     * Show an existing ServiceInventory
     * Returns a ServiceInventory object
     * @param id ID of the resource (required)
     * @return ServiceInventory
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> ServiceInventory info </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public ServiceInventory showServiceInventory(@javax.annotation.Nonnull String id) throws ApiException {
        ApiResponse<ServiceInventory> localVarResp = showServiceInventoryWithHttpInfo(id);
        return localVarResp.getData();
    }

    /**
     * Show an existing ServiceInventory
     * Returns a ServiceInventory object
     * @param id ID of the resource (required)
     * @return ApiResponse&lt;ServiceInventory&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> ServiceInventory info </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ServiceInventory> showServiceInventoryWithHttpInfo(@javax.annotation.Nonnull String id) throws ApiException {
        okhttp3.Call localVarCall = showServiceInventoryValidateBeforeCall(id, null);
        Type localVarReturnType = new TypeToken<ServiceInventory>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Show an existing ServiceInventory (asynchronously)
     * Returns a ServiceInventory object
     * @param id ID of the resource (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> ServiceInventory info </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call showServiceInventoryAsync(@javax.annotation.Nonnull String id, final ApiCallback<ServiceInventory> _callback) throws ApiException {

        okhttp3.Call localVarCall = showServiceInventoryValidateBeforeCall(id, _callback);
        Type localVarReturnType = new TypeToken<ServiceInventory>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for tagServiceInventory
     * @param id ID of the resource (required)
     * @param tag Tag attributes to add (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> ServiceInventory tagged successful </td><td>  -  </td></tr>
        <tr><td> 304 </td><td> Not modified </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call tagServiceInventoryCall(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull List<Tag> tag, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = tag;

        // create path and map variables
        String localVarPath = "/service_inventories/{id}/tag"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "UserSecurity" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call tagServiceInventoryValidateBeforeCall(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull List<Tag> tag, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling tagServiceInventory(Async)");
        }

        // verify the required parameter 'tag' is set
        if (tag == null) {
            throw new ApiException("Missing the required parameter 'tag' when calling tagServiceInventory(Async)");
        }

        return tagServiceInventoryCall(id, tag, _callback);

    }

    /**
     * Tag a ServiceInventory
     * Tags a ServiceInventory object
     * @param id ID of the resource (required)
     * @param tag Tag attributes to add (required)
     * @return List&lt;Tag&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> ServiceInventory tagged successful </td><td>  -  </td></tr>
        <tr><td> 304 </td><td> Not modified </td><td>  -  </td></tr>
     </table>
     */
    public List<Tag> tagServiceInventory(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull List<Tag> tag) throws ApiException {
        ApiResponse<List<Tag>> localVarResp = tagServiceInventoryWithHttpInfo(id, tag);
        return localVarResp.getData();
    }

    /**
     * Tag a ServiceInventory
     * Tags a ServiceInventory object
     * @param id ID of the resource (required)
     * @param tag Tag attributes to add (required)
     * @return ApiResponse&lt;List&lt;Tag&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> ServiceInventory tagged successful </td><td>  -  </td></tr>
        <tr><td> 304 </td><td> Not modified </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<Tag>> tagServiceInventoryWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull List<Tag> tag) throws ApiException {
        okhttp3.Call localVarCall = tagServiceInventoryValidateBeforeCall(id, tag, null);
        Type localVarReturnType = new TypeToken<List<Tag>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Tag a ServiceInventory (asynchronously)
     * Tags a ServiceInventory object
     * @param id ID of the resource (required)
     * @param tag Tag attributes to add (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> ServiceInventory tagged successful </td><td>  -  </td></tr>
        <tr><td> 304 </td><td> Not modified </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call tagServiceInventoryAsync(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull List<Tag> tag, final ApiCallback<List<Tag>> _callback) throws ApiException {

        okhttp3.Call localVarCall = tagServiceInventoryValidateBeforeCall(id, tag, _callback);
        Type localVarReturnType = new TypeToken<List<Tag>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for untagServiceInventory
     * @param id ID of the resource (required)
     * @param tag Tag attributes to removed (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> ServiceInventory untagged successfully </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call untagServiceInventoryCall(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull List<Tag> tag, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = tag;

        // create path and map variables
        String localVarPath = "/service_inventories/{id}/untag"
            .replace("{" + "id" + "}", localVarApiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "UserSecurity" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call untagServiceInventoryValidateBeforeCall(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull List<Tag> tag, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling untagServiceInventory(Async)");
        }

        // verify the required parameter 'tag' is set
        if (tag == null) {
            throw new ApiException("Missing the required parameter 'tag' when calling untagServiceInventory(Async)");
        }

        return untagServiceInventoryCall(id, tag, _callback);

    }

    /**
     * Untag a ServiceInventory
     * Untags a ServiceInventory object
     * @param id ID of the resource (required)
     * @param tag Tag attributes to removed (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> ServiceInventory untagged successfully </td><td>  -  </td></tr>
     </table>
     */
    public void untagServiceInventory(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull List<Tag> tag) throws ApiException {
        untagServiceInventoryWithHttpInfo(id, tag);
    }

    /**
     * Untag a ServiceInventory
     * Untags a ServiceInventory object
     * @param id ID of the resource (required)
     * @param tag Tag attributes to removed (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> ServiceInventory untagged successfully </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> untagServiceInventoryWithHttpInfo(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull List<Tag> tag) throws ApiException {
        okhttp3.Call localVarCall = untagServiceInventoryValidateBeforeCall(id, tag, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Untag a ServiceInventory (asynchronously)
     * Untags a ServiceInventory object
     * @param id ID of the resource (required)
     * @param tag Tag attributes to removed (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 204 </td><td> ServiceInventory untagged successfully </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call untagServiceInventoryAsync(@javax.annotation.Nonnull String id, @javax.annotation.Nonnull List<Tag> tag, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = untagServiceInventoryValidateBeforeCall(id, tag, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
}
