/*
 * Catalog Inventory
 * Catalog Inventory
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServiceOffering
 */
public class ServiceOfferingTest {
    private final ServiceOffering model = new ServiceOffering();

    /**
     * Model tests for ServiceOffering
     */
    @Test
    public void testServiceOffering() {
        // TODO: test ServiceOffering
    }

    /**
     * Test the property 'archivedAt'
     */
    @Test
    public void archivedAtTest() {
        // TODO: test archivedAt
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'distributor'
     */
    @Test
    public void distributorTest() {
        // TODO: test distributor
    }

    /**
     * Test the property 'documentationUrl'
     */
    @Test
    public void documentationUrlTest() {
        // TODO: test documentationUrl
    }

    /**
     * Test the property 'extra'
     */
    @Test
    public void extraTest() {
        // TODO: test extra
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'lastSeenAt'
     */
    @Test
    public void lastSeenAtTest() {
        // TODO: test lastSeenAt
    }

    /**
     * Test the property 'longDescription'
     */
    @Test
    public void longDescriptionTest() {
        // TODO: test longDescription
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'refreshStatePartId'
     */
    @Test
    public void refreshStatePartIdTest() {
        // TODO: test refreshStatePartId
    }

    /**
     * Test the property 'serviceInventoryId'
     */
    @Test
    public void serviceInventoryIdTest() {
        // TODO: test serviceInventoryId
    }

    /**
     * Test the property 'sourceCreatedAt'
     */
    @Test
    public void sourceCreatedAtTest() {
        // TODO: test sourceCreatedAt
    }

    /**
     * Test the property 'sourceDeletedAt'
     */
    @Test
    public void sourceDeletedAtTest() {
        // TODO: test sourceDeletedAt
    }

    /**
     * Test the property 'sourceId'
     */
    @Test
    public void sourceIdTest() {
        // TODO: test sourceId
    }

    /**
     * Test the property 'sourceRef'
     */
    @Test
    public void sourceRefTest() {
        // TODO: test sourceRef
    }

    /**
     * Test the property 'supportUrl'
     */
    @Test
    public void supportUrlTest() {
        // TODO: test supportUrl
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

}
