/*
 * Catalog Inventory
 * Catalog Inventory
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ServicePlan
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T15:52:38.078172+05:30[Asia/Kolkata]", comments = "Generator version: 7.15.0")
public class ServicePlan {
  public static final String SERIALIZED_NAME_ARCHIVED_AT = "archived_at";
  @SerializedName(SERIALIZED_NAME_ARCHIVED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime archivedAt;

  public static final String SERIALIZED_NAME_CREATE_JSON_SCHEMA = "create_json_schema";
  @SerializedName(SERIALIZED_NAME_CREATE_JSON_SCHEMA)
  @javax.annotation.Nullable
  private Object createJsonSchema;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_EXTRA = "extra";
  @SerializedName(SERIALIZED_NAME_EXTRA)
  @javax.annotation.Nullable
  private Object extra;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_LAST_SEEN_AT = "last_seen_at";
  @SerializedName(SERIALIZED_NAME_LAST_SEEN_AT)
  @javax.annotation.Nullable
  private OffsetDateTime lastSeenAt;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_REFRESH_STATE_PART_ID = "refresh_state_part_id";
  @SerializedName(SERIALIZED_NAME_REFRESH_STATE_PART_ID)
  @javax.annotation.Nullable
  private String refreshStatePartId;

  public static final String SERIALIZED_NAME_RESOURCE_VERSION = "resource_version";
  @SerializedName(SERIALIZED_NAME_RESOURCE_VERSION)
  @javax.annotation.Nullable
  private String resourceVersion;

  public static final String SERIALIZED_NAME_SERVICE_OFFERING_ID = "service_offering_id";
  @SerializedName(SERIALIZED_NAME_SERVICE_OFFERING_ID)
  @javax.annotation.Nullable
  private String serviceOfferingId;

  public static final String SERIALIZED_NAME_SOURCE_CREATED_AT = "source_created_at";
  @SerializedName(SERIALIZED_NAME_SOURCE_CREATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime sourceCreatedAt;

  public static final String SERIALIZED_NAME_SOURCE_DELETED_AT = "source_deleted_at";
  @SerializedName(SERIALIZED_NAME_SOURCE_DELETED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime sourceDeletedAt;

  public static final String SERIALIZED_NAME_SOURCE_ID = "source_id";
  @SerializedName(SERIALIZED_NAME_SOURCE_ID)
  @javax.annotation.Nullable
  private String sourceId;

  public static final String SERIALIZED_NAME_SOURCE_REF = "source_ref";
  @SerializedName(SERIALIZED_NAME_SOURCE_REF)
  @javax.annotation.Nullable
  private UUID sourceRef;

  public static final String SERIALIZED_NAME_UPDATE_JSON_SCHEMA = "update_json_schema";
  @SerializedName(SERIALIZED_NAME_UPDATE_JSON_SCHEMA)
  @javax.annotation.Nullable
  private String updateJsonSchema;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime updatedAt;

  public ServicePlan() {
  }

  public ServicePlan(
     OffsetDateTime archivedAt, 
     Object createJsonSchema, 
     OffsetDateTime createdAt, 
     String description, 
     Object extra, 
     String id, 
     OffsetDateTime lastSeenAt, 
     String name, 
     String refreshStatePartId, 
     String resourceVersion, 
     String serviceOfferingId, 
     OffsetDateTime sourceCreatedAt, 
     OffsetDateTime sourceDeletedAt, 
     String sourceId, 
     UUID sourceRef, 
     String updateJsonSchema, 
     OffsetDateTime updatedAt
  ) {
    this();
    this.archivedAt = archivedAt;
    this.createJsonSchema = createJsonSchema;
    this.createdAt = createdAt;
    this.description = description;
    this.extra = extra;
    this.id = id;
    this.lastSeenAt = lastSeenAt;
    this.name = name;
    this.refreshStatePartId = refreshStatePartId;
    this.resourceVersion = resourceVersion;
    this.serviceOfferingId = serviceOfferingId;
    this.sourceCreatedAt = sourceCreatedAt;
    this.sourceDeletedAt = sourceDeletedAt;
    this.sourceId = sourceId;
    this.sourceRef = sourceRef;
    this.updateJsonSchema = updateJsonSchema;
    this.updatedAt = updatedAt;
  }

  /**
   * Get archivedAt
   * @return archivedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getArchivedAt() {
    return archivedAt;
  }



  /**
   * Get createJsonSchema
   * @return createJsonSchema
   */
  @javax.annotation.Nullable
  public Object getCreateJsonSchema() {
    return createJsonSchema;
  }



  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }



  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }



  /**
   * Extra information about this object in JSON format
   * @return extra
   */
  @javax.annotation.Nullable
  public Object getExtra() {
    return extra;
  }



  /**
   * ID of the resource
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }



  /**
   * Get lastSeenAt
   * @return lastSeenAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getLastSeenAt() {
    return lastSeenAt;
  }



  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }



  /**
   * ID of the resource
   * @return refreshStatePartId
   */
  @javax.annotation.Nullable
  public String getRefreshStatePartId() {
    return refreshStatePartId;
  }



  /**
   * Get resourceVersion
   * @return resourceVersion
   */
  @javax.annotation.Nullable
  public String getResourceVersion() {
    return resourceVersion;
  }



  /**
   * ID of the resource
   * @return serviceOfferingId
   */
  @javax.annotation.Nullable
  public String getServiceOfferingId() {
    return serviceOfferingId;
  }



  /**
   * Get sourceCreatedAt
   * @return sourceCreatedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getSourceCreatedAt() {
    return sourceCreatedAt;
  }



  /**
   * Get sourceDeletedAt
   * @return sourceDeletedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getSourceDeletedAt() {
    return sourceDeletedAt;
  }



  /**
   * ID of the resource
   * @return sourceId
   */
  @javax.annotation.Nullable
  public String getSourceId() {
    return sourceId;
  }



  /**
   * Get sourceRef
   * @return sourceRef
   */
  @javax.annotation.Nullable
  public UUID getSourceRef() {
    return sourceRef;
  }



  /**
   * Get updateJsonSchema
   * @return updateJsonSchema
   */
  @javax.annotation.Nullable
  public String getUpdateJsonSchema() {
    return updateJsonSchema;
  }



  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServicePlan servicePlan = (ServicePlan) o;
    return Objects.equals(this.archivedAt, servicePlan.archivedAt) &&
        Objects.equals(this.createJsonSchema, servicePlan.createJsonSchema) &&
        Objects.equals(this.createdAt, servicePlan.createdAt) &&
        Objects.equals(this.description, servicePlan.description) &&
        Objects.equals(this.extra, servicePlan.extra) &&
        Objects.equals(this.id, servicePlan.id) &&
        Objects.equals(this.lastSeenAt, servicePlan.lastSeenAt) &&
        Objects.equals(this.name, servicePlan.name) &&
        Objects.equals(this.refreshStatePartId, servicePlan.refreshStatePartId) &&
        Objects.equals(this.resourceVersion, servicePlan.resourceVersion) &&
        Objects.equals(this.serviceOfferingId, servicePlan.serviceOfferingId) &&
        Objects.equals(this.sourceCreatedAt, servicePlan.sourceCreatedAt) &&
        Objects.equals(this.sourceDeletedAt, servicePlan.sourceDeletedAt) &&
        Objects.equals(this.sourceId, servicePlan.sourceId) &&
        Objects.equals(this.sourceRef, servicePlan.sourceRef) &&
        Objects.equals(this.updateJsonSchema, servicePlan.updateJsonSchema) &&
        Objects.equals(this.updatedAt, servicePlan.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(archivedAt, createJsonSchema, createdAt, description, extra, id, lastSeenAt, name, refreshStatePartId, resourceVersion, serviceOfferingId, sourceCreatedAt, sourceDeletedAt, sourceId, sourceRef, updateJsonSchema, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServicePlan {\n");
    sb.append("    archivedAt: ").append(toIndentedString(archivedAt)).append("\n");
    sb.append("    createJsonSchema: ").append(toIndentedString(createJsonSchema)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    extra: ").append(toIndentedString(extra)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lastSeenAt: ").append(toIndentedString(lastSeenAt)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    refreshStatePartId: ").append(toIndentedString(refreshStatePartId)).append("\n");
    sb.append("    resourceVersion: ").append(toIndentedString(resourceVersion)).append("\n");
    sb.append("    serviceOfferingId: ").append(toIndentedString(serviceOfferingId)).append("\n");
    sb.append("    sourceCreatedAt: ").append(toIndentedString(sourceCreatedAt)).append("\n");
    sb.append("    sourceDeletedAt: ").append(toIndentedString(sourceDeletedAt)).append("\n");
    sb.append("    sourceId: ").append(toIndentedString(sourceId)).append("\n");
    sb.append("    sourceRef: ").append(toIndentedString(sourceRef)).append("\n");
    sb.append("    updateJsonSchema: ").append(toIndentedString(updateJsonSchema)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("archived_at", "create_json_schema", "created_at", "description", "extra", "id", "last_seen_at", "name", "refresh_state_part_id", "resource_version", "service_offering_id", "source_created_at", "source_deleted_at", "source_id", "source_ref", "update_json_schema", "updated_at"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ServicePlan
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ServicePlan.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ServicePlan is not found in the empty JSON string", ServicePlan.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ServicePlan.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ServicePlan` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("refresh_state_part_id") != null && !jsonObj.get("refresh_state_part_id").isJsonNull()) && !jsonObj.get("refresh_state_part_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `refresh_state_part_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("refresh_state_part_id").toString()));
      }
      if ((jsonObj.get("resource_version") != null && !jsonObj.get("resource_version").isJsonNull()) && !jsonObj.get("resource_version").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `resource_version` to be a primitive type in the JSON string but got `%s`", jsonObj.get("resource_version").toString()));
      }
      if ((jsonObj.get("service_offering_id") != null && !jsonObj.get("service_offering_id").isJsonNull()) && !jsonObj.get("service_offering_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `service_offering_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("service_offering_id").toString()));
      }
      if ((jsonObj.get("source_id") != null && !jsonObj.get("source_id").isJsonNull()) && !jsonObj.get("source_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `source_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("source_id").toString()));
      }
      if ((jsonObj.get("source_ref") != null && !jsonObj.get("source_ref").isJsonNull()) && !jsonObj.get("source_ref").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `source_ref` to be a primitive type in the JSON string but got `%s`", jsonObj.get("source_ref").toString()));
      }
      if ((jsonObj.get("update_json_schema") != null && !jsonObj.get("update_json_schema").isJsonNull()) && !jsonObj.get("update_json_schema").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `update_json_schema` to be a primitive type in the JSON string but got `%s`", jsonObj.get("update_json_schema").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ServicePlan.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ServicePlan' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ServicePlan> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ServicePlan.class));

       return (TypeAdapter<T>) new TypeAdapter<ServicePlan>() {
           @Override
           public void write(JsonWriter out, ServicePlan value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ServicePlan read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ServicePlan given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ServicePlan
   * @throws IOException if the JSON string is invalid with respect to ServicePlan
   */
  public static ServicePlan fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ServicePlan.class);
  }

  /**
   * Convert an instance of ServicePlan to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

