/*
 * Catalog Inventory
 * Catalog Inventory
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ServiceInventory
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T15:52:38.078172+05:30[Asia/Kolkata]", comments = "Generator version: 7.15.0")
public class ServiceInventory {
  public static final String SERIALIZED_NAME_ARCHIVED_AT = "archived_at";
  @SerializedName(SERIALIZED_NAME_ARCHIVED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime archivedAt;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_EXTRA = "extra";
  @SerializedName(SERIALIZED_NAME_EXTRA)
  @javax.annotation.Nullable
  private Object extra;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_LAST_SEEN_AT = "last_seen_at";
  @SerializedName(SERIALIZED_NAME_LAST_SEEN_AT)
  @javax.annotation.Nullable
  private OffsetDateTime lastSeenAt;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_REFRESH_STATE_PART_ID = "refresh_state_part_id";
  @SerializedName(SERIALIZED_NAME_REFRESH_STATE_PART_ID)
  @javax.annotation.Nullable
  private String refreshStatePartId;

  public static final String SERIALIZED_NAME_SOURCE_CREATED_AT = "source_created_at";
  @SerializedName(SERIALIZED_NAME_SOURCE_CREATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime sourceCreatedAt;

  public static final String SERIALIZED_NAME_SOURCE_ID = "source_id";
  @SerializedName(SERIALIZED_NAME_SOURCE_ID)
  @javax.annotation.Nullable
  private String sourceId;

  public static final String SERIALIZED_NAME_SOURCE_REF = "source_ref";
  @SerializedName(SERIALIZED_NAME_SOURCE_REF)
  @javax.annotation.Nullable
  private String sourceRef;

  public static final String SERIALIZED_NAME_SOURCE_UPDATED_AT = "source_updated_at";
  @SerializedName(SERIALIZED_NAME_SOURCE_UPDATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime sourceUpdatedAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updated_at";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime updatedAt;

  public ServiceInventory() {
  }

  public ServiceInventory(
     OffsetDateTime archivedAt, 
     OffsetDateTime createdAt, 
     String description, 
     Object extra, 
     String id, 
     OffsetDateTime lastSeenAt, 
     String name, 
     String refreshStatePartId, 
     OffsetDateTime sourceCreatedAt, 
     String sourceId, 
     String sourceRef, 
     OffsetDateTime sourceUpdatedAt, 
     OffsetDateTime updatedAt
  ) {
    this();
    this.archivedAt = archivedAt;
    this.createdAt = createdAt;
    this.description = description;
    this.extra = extra;
    this.id = id;
    this.lastSeenAt = lastSeenAt;
    this.name = name;
    this.refreshStatePartId = refreshStatePartId;
    this.sourceCreatedAt = sourceCreatedAt;
    this.sourceId = sourceId;
    this.sourceRef = sourceRef;
    this.sourceUpdatedAt = sourceUpdatedAt;
    this.updatedAt = updatedAt;
  }

  /**
   * Get archivedAt
   * @return archivedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getArchivedAt() {
    return archivedAt;
  }



  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }



  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }



  /**
   * Get extra
   * @return extra
   */
  @javax.annotation.Nullable
  public Object getExtra() {
    return extra;
  }



  /**
   * ID of the resource
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }



  /**
   * Get lastSeenAt
   * @return lastSeenAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getLastSeenAt() {
    return lastSeenAt;
  }



  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }



  /**
   * ID of the resource
   * @return refreshStatePartId
   */
  @javax.annotation.Nullable
  public String getRefreshStatePartId() {
    return refreshStatePartId;
  }



  /**
   * Get sourceCreatedAt
   * @return sourceCreatedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getSourceCreatedAt() {
    return sourceCreatedAt;
  }



  /**
   * ID of the resource
   * @return sourceId
   */
  @javax.annotation.Nullable
  public String getSourceId() {
    return sourceId;
  }



  /**
   * Get sourceRef
   * @return sourceRef
   */
  @javax.annotation.Nullable
  public String getSourceRef() {
    return sourceRef;
  }



  /**
   * Get sourceUpdatedAt
   * @return sourceUpdatedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getSourceUpdatedAt() {
    return sourceUpdatedAt;
  }



  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceInventory serviceInventory = (ServiceInventory) o;
    return Objects.equals(this.archivedAt, serviceInventory.archivedAt) &&
        Objects.equals(this.createdAt, serviceInventory.createdAt) &&
        Objects.equals(this.description, serviceInventory.description) &&
        Objects.equals(this.extra, serviceInventory.extra) &&
        Objects.equals(this.id, serviceInventory.id) &&
        Objects.equals(this.lastSeenAt, serviceInventory.lastSeenAt) &&
        Objects.equals(this.name, serviceInventory.name) &&
        Objects.equals(this.refreshStatePartId, serviceInventory.refreshStatePartId) &&
        Objects.equals(this.sourceCreatedAt, serviceInventory.sourceCreatedAt) &&
        Objects.equals(this.sourceId, serviceInventory.sourceId) &&
        Objects.equals(this.sourceRef, serviceInventory.sourceRef) &&
        Objects.equals(this.sourceUpdatedAt, serviceInventory.sourceUpdatedAt) &&
        Objects.equals(this.updatedAt, serviceInventory.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(archivedAt, createdAt, description, extra, id, lastSeenAt, name, refreshStatePartId, sourceCreatedAt, sourceId, sourceRef, sourceUpdatedAt, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceInventory {\n");
    sb.append("    archivedAt: ").append(toIndentedString(archivedAt)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    extra: ").append(toIndentedString(extra)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lastSeenAt: ").append(toIndentedString(lastSeenAt)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    refreshStatePartId: ").append(toIndentedString(refreshStatePartId)).append("\n");
    sb.append("    sourceCreatedAt: ").append(toIndentedString(sourceCreatedAt)).append("\n");
    sb.append("    sourceId: ").append(toIndentedString(sourceId)).append("\n");
    sb.append("    sourceRef: ").append(toIndentedString(sourceRef)).append("\n");
    sb.append("    sourceUpdatedAt: ").append(toIndentedString(sourceUpdatedAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("archived_at", "created_at", "description", "extra", "id", "last_seen_at", "name", "refresh_state_part_id", "source_created_at", "source_id", "source_ref", "source_updated_at", "updated_at"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ServiceInventory
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ServiceInventory.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ServiceInventory is not found in the empty JSON string", ServiceInventory.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ServiceInventory.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ServiceInventory` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("refresh_state_part_id") != null && !jsonObj.get("refresh_state_part_id").isJsonNull()) && !jsonObj.get("refresh_state_part_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `refresh_state_part_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("refresh_state_part_id").toString()));
      }
      if ((jsonObj.get("source_id") != null && !jsonObj.get("source_id").isJsonNull()) && !jsonObj.get("source_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `source_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("source_id").toString()));
      }
      if ((jsonObj.get("source_ref") != null && !jsonObj.get("source_ref").isJsonNull()) && !jsonObj.get("source_ref").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `source_ref` to be a primitive type in the JSON string but got `%s`", jsonObj.get("source_ref").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ServiceInventory.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ServiceInventory' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ServiceInventory> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ServiceInventory.class));

       return (TypeAdapter<T>) new TypeAdapter<ServiceInventory>() {
           @Override
           public void write(JsonWriter out, ServiceInventory value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ServiceInventory read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ServiceInventory given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ServiceInventory
   * @throws IOException if the JSON string is invalid with respect to ServiceInventory
   */
  public static ServiceInventory fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ServiceInventory.class);
  }

  /**
   * Convert an instance of ServiceInventory to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

