/*
 * Catalog Inventory
 * Catalog Inventory
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.GraphQLRequest;
import org.openapitools.client.model.GraphQLResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Disabled
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * Return this API document in JSON format
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDocumentationTest() throws ApiException {
        Object response = api.getDocumentation();
        // TODO: test validations
    }

    /**
     * Perform a GraphQL Query
     *
     * Performs a GraphQL Query
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void postGraphQLTest() throws ApiException {
        GraphQLRequest graphQLRequest = null;
        GraphQLResponse response = api.postGraphQL(graphQLRequest);
        // TODO: test validations
    }

}
