/*
 * Catalog Inventory
 * Catalog Inventory
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ErrorNotFound;
import org.openapitools.client.model.ServicePlan;
import org.openapitools.client.model.ServicePlansCollection;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ServicePlanApi
 */
@Disabled
public class ServicePlanApiTest {

    private final ServicePlanApi api = new ServicePlanApi();

    /**
     * List ServicePlans
     *
     * Returns an array of ServicePlan objects
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listServicePlansTest() throws ApiException {
        Integer limit = null;
        Integer offset = null;
        Object filter = null;
        Object sortBy = null;
        ServicePlansCollection response = api.listServicePlans(limit, offset, filter, sortBy);
        // TODO: test validations
    }

    /**
     * Show an existing ServicePlan
     *
     * Returns a ServicePlan object
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void showServicePlanTest() throws ApiException {
        String id = null;
        ServicePlan response = api.showServicePlan(id);
        // TODO: test validations
    }

}
