/*
 * Catalog Inventory
 * Catalog Inventory
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ErrorNotFound;
import org.openapitools.client.model.ServiceOfferingNode;
import org.openapitools.client.model.ServiceOfferingNodesCollection;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ServiceOfferingNodeApi
 */
@Disabled
public class ServiceOfferingNodeApiTest {

    private final ServiceOfferingNodeApi api = new ServiceOfferingNodeApi();

    /**
     * List ServiceOfferingNodes
     *
     * Returns an array of ServiceOfferingNode objects
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listServiceOfferingNodesTest() throws ApiException {
        Integer limit = null;
        Integer offset = null;
        Object filter = null;
        Object sortBy = null;
        ServiceOfferingNodesCollection response = api.listServiceOfferingNodes(limit, offset, filter, sortBy);
        // TODO: test validations
    }

    /**
     * Show an existing ServiceOfferingNode
     *
     * Returns a ServiceOfferingNode object
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void showServiceOfferingNodeTest() throws ApiException {
        String id = null;
        ServiceOfferingNode response = api.showServiceOfferingNode(id);
        // TODO: test validations
    }

}
