/*
 * Catalog Inventory
 * Catalog Inventory
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ErrorNotFound;
import org.openapitools.client.model.ServiceCredential;
import org.openapitools.client.model.ServiceCredentialsCollection;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ServiceCredentialApi
 */
@Disabled
public class ServiceCredentialApiTest {

    private final ServiceCredentialApi api = new ServiceCredentialApi();

    /**
     * List ServiceCredentials
     *
     * Returns an array of ServiceCredential objects
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listServiceCredentialsTest() throws ApiException {
        Integer limit = null;
        Integer offset = null;
        Object filter = null;
        Object sortBy = null;
        ServiceCredentialsCollection response = api.listServiceCredentials(limit, offset, filter, sortBy);
        // TODO: test validations
    }

    /**
     * Show an existing ServiceCredential
     *
     * Returns a ServiceCredential object
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void showServiceCredentialTest() throws ApiException {
        String id = null;
        ServiceCredential response = api.showServiceCredential(id);
        // TODO: test validations
    }

}
