/*
 * Catalog Inventory
 * Catalog Inventory
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ErrorNotFound;
import org.openapitools.client.model.ServiceInstance;
import org.openapitools.client.model.ServiceInstancesCollection;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ServiceInstanceApi
 */
@Disabled
public class ServiceInstanceApiTest {

    private final ServiceInstanceApi api = new ServiceInstanceApi();

    /**
     * List ServiceInstances
     *
     * Returns an array of ServiceInstance objects
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listServiceInstancesTest() throws ApiException {
        Integer limit = null;
        Integer offset = null;
        Object filter = null;
        Object sortBy = null;
        ServiceInstancesCollection response = api.listServiceInstances(limit, offset, filter, sortBy);
        // TODO: test validations
    }

    /**
     * Show an existing ServiceInstance
     *
     * Returns a ServiceInstance object
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void showServiceInstanceTest() throws ApiException {
        String id = null;
        ServiceInstance response = api.showServiceInstance(id);
        // TODO: test validations
    }

}
