/*
 * Catalog Inventory
 * Catalog Inventory
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ErrorNotFound;
import org.openapitools.client.model.ServiceInventoriesCollection;
import org.openapitools.client.model.ServiceInventory;
import org.openapitools.client.model.Tag;
import org.openapitools.client.model.TagsCollection;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ServiceInventoryApi
 */
@Disabled
public class ServiceInventoryApiTest {

    private final ServiceInventoryApi api = new ServiceInventoryApi();

    /**
     * List ServiceInventories
     *
     * Returns an array of ServiceInventory objects
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listServiceInventoriesTest() throws ApiException {
        Integer limit = null;
        Integer offset = null;
        Object filter = null;
        Object sortBy = null;
        ServiceInventoriesCollection response = api.listServiceInventories(limit, offset, filter, sortBy);
        // TODO: test validations
    }

    /**
     * List Tags for ServiceInventory
     *
     * Returns an array of Tag objects
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listServiceInventoryTagsTest() throws ApiException {
        String id = null;
        Integer limit = null;
        Integer offset = null;
        Object filter = null;
        Object sortBy = null;
        TagsCollection response = api.listServiceInventoryTags(id, limit, offset, filter, sortBy);
        // TODO: test validations
    }

    /**
     * Show an existing ServiceInventory
     *
     * Returns a ServiceInventory object
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void showServiceInventoryTest() throws ApiException {
        String id = null;
        ServiceInventory response = api.showServiceInventory(id);
        // TODO: test validations
    }

    /**
     * Tag a ServiceInventory
     *
     * Tags a ServiceInventory object
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void tagServiceInventoryTest() throws ApiException {
        String id = null;
        List<Tag> tag = null;
        List<Tag> response = api.tagServiceInventory(id, tag);
        // TODO: test validations
    }

    /**
     * Untag a ServiceInventory
     *
     * Untags a ServiceInventory object
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void untagServiceInventoryTest() throws ApiException {
        String id = null;
        List<Tag> tag = null;
        api.untagServiceInventory(id, tag);
        // TODO: test validations
    }

}
