/*
 * Catalog Inventory
 * Catalog Inventory
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ErrorNotFound;
import org.openapitools.client.model.Task;
import org.openapitools.client.model.TasksCollection;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TaskApi
 */
@Disabled
public class TaskApiTest {

    private final TaskApi api = new TaskApi();

    /**
     * List Tasks
     *
     * Returns an array of Task objects
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listTasksTest() throws ApiException {
        Integer limit = null;
        Integer offset = null;
        Object filter = null;
        Object sortBy = null;
        TasksCollection response = api.listTasks(limit, offset, filter, sortBy);
        // TODO: test validations
    }

    /**
     * Show an existing Task
     *
     * Returns a Task object
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void showTaskTest() throws ApiException {
        String id = null;
        Task response = api.showTask(id);
        // TODO: test validations
    }

    /**
     * Update an existing Task
     *
     * Updates a Task object
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateTaskTest() throws ApiException {
        String id = null;
        Task task = null;
        api.updateTask(id, task);
        // TODO: test validations
    }

}
